//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picavi.JsonRpc.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Picavi.JsonRpc.Server.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal JSON-RPC error.
        /// </summary>
        internal static string Dsc_InternalError {
            get {
                return ResourceManager.GetString("Dsc_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string Dsc_InternalServerError {
            get {
                return ResourceManager.GetString("Dsc_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Invalid method parameter(s).
        /// </summary>
        internal static string Dsc_InvalidParams {
            get {
                return ResourceManager.GetString("Dsc_InvalidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON sent is not a valid Request object.
        /// </summary>
        internal static string Dsc_InvalidRequest {
            get {
                return ResourceManager.GetString("Dsc_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} does not exist / is not available.
        /// </summary>
        internal static string Dsc_MethodNoFound {
            get {
                return ResourceManager.GetString("Dsc_MethodNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON was received by the server.An error occurred on the server while parsing the JSON text.
        /// </summary>
        internal static string Dsc_ParseError {
            get {
                return ResourceManager.GetString("Dsc_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        internal static string Dsc_ResourceNotFoundError {
            get {
                return ResourceManager.GetString("Dsc_ResourceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for implementation-defined server-errors.
        /// </summary>
        internal static string Dsc_ServerError {
            get {
                return ResourceManager.GetString("Dsc_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string Msg_InternalError {
            get {
                return ResourceManager.GetString("Msg_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerError.
        /// </summary>
        internal static string Msg_InternalServerError {
            get {
                return ResourceManager.GetString("Msg_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid params.
        /// </summary>
        internal static string Msg_InvalidParams {
            get {
                return ResourceManager.GetString("Msg_InvalidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        internal static string Msg_InvalidRequest {
            get {
                return ResourceManager.GetString("Msg_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not found.
        /// </summary>
        internal static string Msg_MethodNotFound {
            get {
                return ResourceManager.GetString("Msg_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string Msg_NotFound {
            get {
                return ResourceManager.GetString("Msg_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error.
        /// </summary>
        internal static string Msg_ParseError {
            get {
                return ResourceManager.GetString("Msg_ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        internal static string Msg_ServerError {
            get {
                return ResourceManager.GetString("Msg_ServerError", resourceCulture);
            }
        }
    }
}
